### PR TITLE
Javadoc + code simplification +

### PR DESCRIPTION
**Pull request by mukoki**
Method signature simplified in CoordinateOperationFactory

### CODE REVIEW

**Comment by ebocher** [comment]
The merge is planned before the end of February. Sorry for the delay.

**Comment by ebocher** [comment]
@mukoki .
I' m not able to compile this PR due to a bad class name. worldRegistry must be replaced by WorldRegistry. 
Anyway, org.cts.op.CirceMetropoleComplianceTest class contains 4 assertion errors.
So I cannot merge before you fixe them.

**Comment by mukoki** [comment]
Hi Erwan,

I just made some more fixes in CTS today and pushed them from my local 
project.
(I don't remember if I must also create a PullRequest from Github - let 
me know).
I have changed worldRegistry to WorldRegistry in my code a long time 
ago. I don't know why you don't get it.
About tests which do not pass, I made some fixes and deactivated a test 
on New Caledonia (I wrote a comment about this test).

Best regards,

Michaël

**Comment by ebocher** [comment]
Dear @mukoki ,

Thanks a lot but I m not able to build the last PR. 4 tests are in errors.

```java
testLAMBE_to_ETRS_LCC(org.cts.op.CirceMetropoleComplianceTest)  Time elapsed: 0.021 sec  <<< FAILURE!
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:92)
	at org.junit.Assert.assertTrue(Assert.java:43)
	at org.junit.Assert.assertTrue(Assert.java:54)
	at org.cts.op.BaseCoordinateTransformTest.test(BaseCoordinateTransformTest.java:136)
	at org.cts.op.CirceMetropoleComplianceTest.testLAMBE_to_ETRS_LCC(CirceMetropoleComplianceTest.java:359)

testLAMBE_to_ETRS_LAEA(org.cts.op.CirceMetropoleComplianceTest)  Time elapsed: 0.041 sec  <<< FAILURE!
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:92)
	at org.junit.Assert.assertTrue(Assert.java:43)
	at org.junit.Assert.assertTrue(Assert.java:54)
	at org.cts.op.BaseCoordinateTransformTest.test(BaseCoordinateTransformTest.java:136)
	at org.cts.op.CirceMetropoleComplianceTest.testLAMBE_to_ETRS_LAEA(CirceMetropoleComplianceTest.java:364)

testLAMBE_to_ETRS_UTM32N(org.cts.op.CirceMetropoleComplianceTest)  Time elapsed: 0.02 sec  <<< FAILURE!
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:92)
	at org.junit.Assert.assertTrue(Assert.java:43)
	at org.junit.Assert.assertTrue(Assert.java:54)
	at org.cts.op.BaseCoordinateTransformTest.test(BaseCoordinateTransformTest.java:136)
	at org.cts.op.CirceMetropoleComplianceTest.testLAMBE_to_ETRS_UTM32N(CirceMetropoleComplianceTest.java:369)

testNTF_P_GEO2D_EGM2008_To_WGS84_C(org.cts.op.CirceMetropoleComplianceTest)  Time elapsed: 0.003 sec  <<< FAILURE!
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:92)
	at org.junit.Assert.assertTrue(Assert.java:43)
	at org.junit.Assert.assertTrue(Assert.java:54)
	at org.cts.op.BaseCoordinateTransformTest.test(BaseCoordinateTransformTest.java:132)
	at org.cts.op.CirceMetropoleComplianceTest.testNTF_P_GEO2D_EGM2008_To_WGS84_C(CirceMetropoleComplianceTest.java:247)
```

**Comment by ebocher** [comment]
dear @mukoki . Any input about this errors.

**Comment by mukoki** [comment]
WorldRegistry typo is resolved on my side.
I deactivated some test on new caledonia (previous pull request). It failed, but it is not clear for me which algo  / parameters is used by circe.
One test failed because egm08fr.mnt was missing (it is quite a big file !). I added it to the repository.
I've now 231/231 tests passing. I'm not sure I solved all the failure you get, but I have no more on my machine.
Note : a few months ago, I observed that results were varying depending on the jvm (7 vs 8) ! It was small variations and I don't think it can make tests fail. But I was surprised that double calculations is not perfectly predictable.

**Comment by ebocher** [comment]
I will look on it asap. 
About the new grid file, maybe we have to think about an extension mechanism ? 
Otherwise the CTS binary distribution will be too big.

**Comment by nicolas-f** [comment]
For the next minor release, we could create another optional maven projects for each grid based registry collection.
Something like cts-epsg-egm. What do you think ?

**Comment by ebocher** [comment]
This integration is planed before the end of the year.
Some refactoring will be done  to manage grid file dependencies.

**Comment by mukoki** [comment]
I fixed a bug in CoordinateSequence simplification mechanism, improved Projection.inverse operations, improved/add comments on CompoundCRS and add some finnish projection. This version may not be compatible with the previous one.

**Comment by ebocher** [comment]
Thanks a lot.
I will look on it asap.
We are a bit busy since the new team location in Vannes.

**Comment by ebocher** [comment]
We must find a solution to manage the egm08fr.mnt because this file is too big.

**Comment by ebocher** [comment]
Please could update the pr to resolve the conflicts

**Comment by ebocher** [comment]
c

**Pull request closed without merging**
